[package]
name = "rust-chip-8"
version = "0.1.0"
authors = ["vincios <vinicios.a.ferreira13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.13"
time = "0.1.42"
rand = "0.5.3"

